[package]
name = "logismevo-phone"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "logismevo-phone"

[dependencies]
logismevo_sim = { path = "../sim" }

[target.'cfg(target_os = "linux")'.dependencies]
bevy = { version = "0.15", default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_sprite",
    "bevy_asset",
    "bevy_gizmos",
    "png",
    "x11",
    "wayland",
] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
bevy = { version = "0.15", default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_sprite",
    "bevy_asset",
    "bevy_gizmos",
    "png",
] }
